// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "apis": {
    "DictsAPI": {
      /**
       * Destroy
       * @returns {Promise<void>} 
       */
      "Destroy": () => {
        return window.go.apis.DictsAPI.Destroy();
      },
      /**
       * Dicts
       * @returns {Promise<Array<PlainDictItem>>}  - Go Type: []*model.PlainDictItem
       */
      "Dicts": () => {
        return window.go.apis.DictsAPI.Dicts();
      },
      /**
       * LookupDefinition
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {number} arg3 - Go Type: uint64
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "LookupDefinition": (arg1, arg2, arg3) => {
        return window.go.apis.DictsAPI.LookupDefinition(arg1, arg2, arg3);
      },
      /**
       * Suggest
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<Array<WrappedWordItem>|Error>}  - Go Type: []*model.WrappedWordItem
       */
      "Suggest": (arg1) => {
        return window.go.apis.DictsAPI.Suggest(arg1);
      },
    },
    "StaticInfos": {
      /**
       * StaticSrvUrl
       * @returns {Promise<string>}  - Go Type: string
       */
      "StaticSrvUrl": () => {
        return window.go.apis.StaticInfos.StaticSrvUrl();
      },
    },
  },

  "main": {
    "App": {
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
    },
  },

};
export default go;
