// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Destroy() {
  return window['go']['apis']['DictsAPI']['Destroy']();
}

export function Dicts() {
  return window['go']['apis']['DictsAPI']['Dicts']();
}

export function LookupDefinition(arg1, arg2, arg3) {
  return window['go']['apis']['DictsAPI']['LookupDefinition'](arg1, arg2, arg3);
}

export function Suggest(arg1) {
  return window['go']['apis']['DictsAPI']['Suggest'](arg1);
}
