// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Destroy():Promise<void>;

export function Dicts():Promise<Array<model.PlainDictItem>>;

export function LookupDefinition(arg1:string,arg2:string,arg3:number):Promise<string>;

export function Suggest(arg1:string):Promise<Array<model.WrappedWordItem>>;
