// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Dicts():Promise<Array<model.PlainDictionaryItem>>;

export function Locate(arg1:string,arg2:model.KeyBlockEntry):Promise<model.Resp>;

export function Lookup(arg1:string,arg2:string):Promise<model.Resp>;

export function Search(arg1:string,arg2:string):Promise<model.Resp>;
