// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dicts() {
  return window['go']['apis']['DictsAPI']['Dicts']();
}

export function Locate(arg1, arg2) {
  return window['go']['apis']['DictsAPI']['Locate'](arg1, arg2);
}

export function Lookup(arg1, arg2) {
  return window['go']['apis']['DictsAPI']['Lookup'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['apis']['DictsAPI']['Search'](arg1, arg2);
}
