// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dispatch(arg1, arg2) {
  return window['go']['main']['App']['Dispatch'](arg1, arg2);
}

export function ResourceServerAddr() {
  return window['go']['main']['App']['ResourceServerAddr']();
}
