// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Dispatch(arg1:string,arg2:{[key: string]: any}):Promise<model.Resp>;

export function ResourceServerAddr():Promise<string>;
