// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2, arg3);
}

export function BaseDictDir() {
  return window['go']['main']['App']['BaseDictDir']();
}

export function BuildIndexByDictId(arg1) {
  return window['go']['main']['App']['BuildIndexByDictId'](arg1);
}

export function CreateNotebook(arg1) {
  return window['go']['main']['App']['CreateNotebook'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['main']['App']['DeleteNotebook'](arg1);
}

export function GetAllDicts() {
  return window['go']['main']['App']['GetAllDicts']();
}

export function GetBookmarkSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBookmarkSnapshot'](arg1, arg2, arg3);
}

export function GetBookmarks() {
  return window['go']['main']['App']['GetBookmarks']();
}

export function GetNotebooks() {
  return window['go']['main']['App']['GetNotebooks']();
}

export function InitDicts() {
  return window['go']['main']['App']['InitDicts']();
}

export function OpenFinder(arg1) {
  return window['go']['main']['App']['OpenFinder'](arg1);
}

export function RemoveBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveBookmark'](arg1, arg2, arg3);
}

export function RenameNotebook(arg1, arg2) {
  return window['go']['main']['App']['RenameNotebook'](arg1, arg2);
}

export function ResourceServerAddr() {
  return window['go']['main']['App']['ResourceServerAddr']();
}

export function SearchWord(arg1, arg2) {
  return window['go']['main']['App']['SearchWord'](arg1, arg2);
}

export function SetDefaultNotebook(arg1) {
  return window['go']['main']['App']['SetDefaultNotebook'](arg1);
}
